// `agentgate init` — deterministic, non-interactive generation of a safe
// starter AgentGate project (config + policy). Never overwrites existing
// files unless explicitly told to, never writes outside the target
// directory, never embeds a runtime auth token or secret, and always
// generates a deny-by-default policy (Milestone 5).
//
// This module is pure/testable: it returns a description of what it would
// do or did, and the CLI layer (cli.ts) is the only place that prints to
// the console or sets process.exitCode.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

export interface InitOptions {
  /** Directory to initialize into. Created if it does not exist. */
  targetDir: string;
  /** Overwrite existing generated files if present. */
  force: boolean;
}

export interface InitFileOutcome {
  /** Absolute path of the file. */
  path: string;
  /** Path relative to targetDir, for display. */
  relativePath: string;
  action: 'written' | 'skipped-exists';
}

export interface InitResult {
  targetDir: string;
  files: InitFileOutcome[];
  /** True only if every file was actually written (nothing skipped). */
  ok: boolean;
}

const CONFIG_FILE_NAME = 'agentgate.yml';
const POLICY_FILE_NAME = 'agentgate.policy.yml';
const DB_FILE_NAME = 'agentgate.sqlite';

/**
 * Deny-by-default starter policy. Permits exactly one harmless tool
 * ("echo") — narrow by design, not a wildcard allow — so a new user's
 * first `agentgate start` + a real smoke test both have something safe to
 * exercise, without opening broad access to be "easy."
 */
export function buildPolicyTemplate(): string {
  return `# AgentGate policy — generated by \`agentgate init\`.
#
# Deny-by-default: any tool call that does not match a rule below is
# denied. Start narrow and widen deliberately as you add real downstream
# tools — see docs/POLICY_REFERENCE.md for every match field and decision
# type (allow / deny / require_approval / allow_with_transform).
version: 1

defaults:
  # No rule below matched -> deny. Never change this to "allow" without
  # understanding the consequences — see docs/THREAT_MODEL.md.
  decision: deny

rules:
  # Narrow starter rule: allows only a harmless "echo" tool call, matching
  # AgentGate's own built-in \`agentgate smoke-test\` fixture. Replace or
  # extend this with your real downstream server's tool names — never
  # widen it to a bare wildcard just to make setup easier.
  - id: allow-echo
    description: Allow a single harmless example tool call.
    tools: ["echo"]
    decision: allow

  # Example of a higher-risk pattern, commented out: require a human to
  # approve any file write before it happens.
  # - id: approve-file-writes
  #   description: Require approval before writing any file.
  #   tools: ["write_file"]
  #   decision: require_approval
  #   approval_ttl_seconds: 120
`;
}

/**
 * Gateway config template. Loopback-only ports, no embedded auth token
 * (the Control API token is generated fresh per launch and only ever
 * printed to stderr — see docs/ARCHITECTURE.md), and a placeholder
 * downstream server the user must point at their real one.
 */
export function buildConfigTemplate(): string {
  return `# AgentGate gateway configuration — generated by \`agentgate init\`.
#
# Loopback-only by default (127.0.0.1) — do not change gateway_port/
# control_port to bind anywhere else. See docs/ARCHITECTURE.md.
version: 1

gateway_port: 4000
control_port: 4001

policy: ./${POLICY_FILE_NAME}
db_path: ./${DB_FILE_NAME}

# Tool Integrity Registry (rug-pull / tool-definition-poisoning defense).
# "explicit" is the recommended, high-security mode for a NEW project: a new
# or changed downstream tool definition is quarantined until you explicitly
# review and accept its exact fingerprint (\`agentgate tools status\` /
# \`agentgate tools trust <id> --fingerprint <hash>\`). This differs from
# AgentGate's own backwards-compatibility default (omitting this section
# entirely defaults to "monitor" — reporting only, never blocking, kept only
# so pre-existing configs are not silently broken on upgrade). See
# docs/POLICY_REFERENCE.md and ADR-0012 in docs/AI_DECISIONS.md.
tool_integrity:
  mode: explicit

servers:
  # Replace this placeholder with your real downstream MCP server. Until
  # you do, \`agentgate start\` will fail to spawn it — that is expected;
  # run \`agentgate doctor\` after editing this to check your setup, and
  # \`agentgate smoke-test\` to verify AgentGate itself works right now,
  # independent of this file.
  - id: downstream
    transport: stdio
    command: REPLACE_WITH_YOUR_DOWNSTREAM_COMMAND
    args: []
`;
}

/** Resolves `p` relative to `base` and rejects any path that escapes `base` via `..` or an absolute override. */
function resolveInside(base: string, relative: string): string {
  const resolved = path.resolve(base, relative);
  const resolvedBase = path.resolve(base);
  if (resolved !== resolvedBase && !resolved.startsWith(resolvedBase + path.sep)) {
    throw new Error(`Refusing to write outside the target directory: ${resolved}`);
  }
  return resolved;
}

/** Atomic write: write to a sibling temp file, then rename over the destination. */
function writeFileAtomic(destPath: string, content: string): void {
  const tmpPath = `${destPath}.tmp-${crypto.randomBytes(6).toString('hex')}`;
  fs.writeFileSync(tmpPath, content, { encoding: 'utf-8' });
  fs.renameSync(tmpPath, destPath);
}

export function runInit(opts: InitOptions): InitResult {
  const targetDir = path.resolve(opts.targetDir);
  fs.mkdirSync(targetDir, { recursive: true });

  const targets: Array<{ relativePath: string; content: string }> = [
    { relativePath: CONFIG_FILE_NAME, content: buildConfigTemplate() },
    { relativePath: POLICY_FILE_NAME, content: buildPolicyTemplate() },
  ];

  const files: InitFileOutcome[] = [];
  let ok = true;

  for (const target of targets) {
    const absPath = resolveInside(targetDir, target.relativePath);
    const exists = fs.existsSync(absPath);
    if (exists && !opts.force) {
      files.push({ path: absPath, relativePath: target.relativePath, action: 'skipped-exists' });
      ok = false;
      continue;
    }
    writeFileAtomic(absPath, target.content);
    files.push({ path: absPath, relativePath: target.relativePath, action: 'written' });
  }

  return { targetDir, files, ok };
}

export const INIT_FILE_NAMES = { CONFIG_FILE_NAME, POLICY_FILE_NAME, DB_FILE_NAME };
